image: texlive/texlive

compileThesis:
  script:
    - cd src/thesis
    - make
    - make clean
  only:
    changes:
      - src/thesis/**/*
  artifacts:
    paths:
        - src/thesis/ctufit-thesis-en.pdf
    untracked: true
    expire_in: 42 yrs
